# Generated by Django 5.0.6 on 2024-10-04 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0003_alter_datashop_payments_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datashop',
            name='payments_status',
        ),
        migrations.RemoveField(
            model_name='datashop',
            name='products_status',
        ),
    ]
