# Generated by Django 5.0.6 on 2024-10-04 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0004_remove_datashop_payments_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datashop',
            name='payments_status',
            field=models.CharField(choices=[('รอร้านตรวจสอบ', 'Checked'), ('รอการชำระเงิน', 'Pending'), ('ชำระเงินเรียบร้อยแล้ว', 'Paid')], default='รอร้านตรวจสอบ', max_length=50, verbose_name='การชำระเงิน'),
        ),
        migrations.AddField(
            model_name='datashop',
            name='products_status',
            field=models.CharField(choices=[('รอกดรับสินค้า', 'Received'), ('กำลังทำสินค้า', 'Processing'), ('จัดส่งเรียบร้อยแล้ว', 'Shipped')], default='รอกดรับสินค้า', max_length=50, verbose_name='สถานะสินค้า'),
        ),
    ]
